### ISSUE TITLE
Multiple spaces are collapsed

### ISSUE THREAD

**Issue by retorquere** [bdougherty/better-title-case#2]
Would it be possible to keep spacing in the string as-is? The title-casing looks good for my needs but I need to have the resulting string be the same length as the input.

**Comment by bdougherty** [comment]
@retorquere that should be possible. Do you have an example string for your use case, or can you submit a PR with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests)?

**Comment by retorquere** [comment]
Hope I got it right: https://github.com/bdougherty/better-title-case/pull/3
