### ISSUE TITLE
Publish ES5 version to NPM

### ISSUE THREAD

**Issue by AprilArcus** [bdougherty/better-title-case#5]
It's difficult to specifically opt this module into babel in my project config. I'd appreciate it if you could publish a transpiled version to npm.

**Comment by bdougherty** [comment]
@AprilArcus I assume you are looking to use this in a browser?

Note to self: [pikapkg/pack](https://github.com/pikapkg/pack) might be a good option here.

**Comment by AprilArcus** [comment]
Of course. I've already opted this package into babel on my project, but it would be better if I didn't need to. Publishing packages to npm as es5 remains standard practice and ensures compatibility with the lowest common denominator. Of course modules and tree shaking are nice, too, and you can have it both ways by including the es6 `/src` under the `module` field in `package.json` as well.

**Comment by bdougherty** [comment]
This will now be published as an ES module, and it now uses the global URL object, so this should work just fine in browsers now.
