### ISSUE TITLE
Would be handy to have a TypeScript definition file

### ISSUE THREAD

**Issue by CharlesWiltgen** [bdougherty/better-title-case#6]
Thank you for this handy package! My only suggestion is to add an associated TypeScript definition file. (I made a bare-bones one myself.) Microsoft has a tool to help with this: https://github.com/microsoft/dts-gen (Thank you!)

**Comment by bdougherty** [comment]
Thanks for your patience @CharlesWiltgen. I don't have any experience with TypeScript, but I'm happy to add the definition file. Would you mind submitting yours as a PR? Even if it's just something for me to start with.
